server:
  port: 8769
spring:
  application:
    name: backend
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: $trongp@assword170493